spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT_SERVICE
          uri: http://localhost:9551
          predicates:
            - Path=/department/**

        - id: NEWS_SERVICE
          uri: http://localhost:9552
          predicates:
            - Path=/news/**

        - id: BOOK_SERVICE
          uri: http://localhost:9553
          predicates:
            - Path=/book/**

        - id: REGISTRATION-SERVICE
          uri: http://localhost:8017
          predicates:
            - Path=/registration/**

        - id: EMPLOYEE_SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/employee/**

eureka:
  client:
    prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9008
